version: '3'
services:
  web:
    build: .
    environment:
      FLASK_APP: 'dash/dash.py'
      FLASK_DEBUG: 1
    #command: 'python3 -m flask run --host=0.0.0.0 --port=80'
    command: 'uwsgi -s /tmp/web.sock --manage-script-name --mount /dash=dash.wsgi:app --http 0.0.0.0:80'
    network_mode: 'host'
    volumes:
    - .:/app
    ports:
    - 80
